eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:admin123@eureka.sulin.online:8520/eureka/
  instance:
    metadata-map:
      user:
        name: admin
        password: 123456
logging:
  file: logs/boot-admin-sample.log
server:
  port: 5001
spring:
  application:
    name: service-admin
  boot:
    admin:
      routes:
        endpoints: env,metrics,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,loggers,auditevents,hystrix.stream
