eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:admin123@eureka.sulin.online:8520/eureka/

server:
  port: 8762
spring:

  main:
    allow-bean-definition-overriding: true

  application:
    name: service-hi
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #    url: jdbc:mysql://192.168.101.218:6666/spring-cloud-auth?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    url: jdbc:mysql://192.168.101.218:6666/spring-cloud-auth?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: root
    password: 123456

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQLDialect

security:
  oauth2:
    resource:
      user-info-uri: http://localhost:5000/uaa/users/current
    client:
      clientId: service-hi
      clientSecret: 123456
      accessTokenUri: http://localhost:5000/uaa/oauth/token
      grant-type: client_credentials,password
      scope: server


