eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:admin123@eureka.sulin.online:8520/eureka/

server:
  port: 8762
spring:
  application:
    name: user-service
  zipkin:
    base-url: http://192.168.101.29:9411
  sleuth:
    sampler:
      percentage: 1.0
  boot:
    admin:
      client:
        instance:
          prefer-ip: true
        url: http://192.168.101.29:5001
management:
  endpoints:
    health:
      show-details: always
    web:
      exposure:
        base-path: /
        include: '*'

logging:
  file: "/logdata/user-service/userservice_run.log"