eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:admin123@eureka.sulin.online:8520/eureka/
server:
  port:
spring:
  application:
    name: service-lucy
  boot:
    admin:
      client:
        instance:
#          prefer-ip: true
        url: http://localhost:5001
logging:
  file: "logs/eureka-client-one.log"

management:
  endpoints:
    health:
      show-details: always
    web:
      exposure:
        base-path: /
        include: '*'

