spring:
  application:
    name: eureka-feign-client
server:
  port: 8765

eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:admin123@eureka.sulin.online:8520/eureka/
feign:
  hystrix:
    enabled: true